name: Docker Image CI
on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xlws:$(date +%s)
